const CardApi = [
  {
    id: 1,
    img: "./images/kaneki.jpg",
    title: "Life experience with cartoons",
    price: 80,
    star: "",
    reviewCount: 5,
    rating: "5.7",
    country: "JAMAICA",
    openSpots: 0,
    location: " ",
  },
  {
    id: 2,
    img: "./images/itachi.jpg",
    title: "Life experience with cartoons",
    price: 100,
    star: "",
    reviewCount: 6,
    rating: "5.7",
    country: "SCOTLAND",
    openSpots: 20,
    location: "online",
  },
  {
    id: 3,
    img: "./images/nezuko.jpg",
    title: "Life experience with cartoons",
    price: 90,
    star: "",
    reviewCount: 5.5,
    rating: "5.7",
    country: "USA",
    openSpots: 2,
    location: "online",
  },
  {
    id: 4,
    img: "./images/ninja.jpg",
    title: "Life experience with cartoons",
    price: 90,
    star: "",
    reviewCount: 5.5,
    rating: "5.7",
    country: "Ghana",
    openSpots: 10,
    location: "",
  },
  {
    id: 5,
    img: "./images/pin1.jpeg",
    title: "Life experience with cartoons",
    price: 90,
    star: "",
    reviewCount: 5.5,
    rating: "5.7",
    country: "Zambia",
    openSpots: 5,
    location: "online",
  },
  {
    id: 6,
    img: "./images/saitama.jpg",
    title: "Life experience with cartoons",
    price: 90,
    star: "",
    reviewCount: 5.5,
    rating: "5.7",
    country: "Zambia",
    openSpots: 0,
    location: "online",
  },
];
export default CardApi;

//also working
// export default [
//   {
//     id: 1,
//     img: "./images/kaneki.jpg",
//     title: "Life experience with cartoons",
//     price: 80,
//     star: "",
//     reviewCount: 5,
//     rating: "5.7",
//     country: "JAMAICA",
//   },
//   {
//     id: 2,
//     img: "./images/itachi.jpg",
//     title: "Life experience with cartoons",
//     price: 100,
//     star: "",
//     reviewCount: 6,
//     rating: "5.7",
//     country: "SCOTLAND",
//   },
//   {
//     id: 3,
//     img: "./images/nezuko.jpg",
//     title: "Life experience with cartoons",
//     price: 90,
//     star: "",
//     reviewCount: 5.5,
//     rating: "5.7",
//     country: "USA",
//   },
//   {
//     id: 4,
//     img: "./images/ninja.jpg",
//     title: "Life experience with cartoons",
//     price: 90,
//     star: "",
//     reviewCount: 5.5,
//     rating: "5.7",
//     country: "Ghana",
//   },
//   {
//     id: 5,
//     img: "./images/pin1.jpeg",
//     title: "Life experience with cartoons",
//     price: 90,
//     star: "",
//     reviewCount: 5.5,
//     rating: "5.7",
//     country: "Zambia",
//   },
//   {
//     id: 6,
//     img: "./images/saitama.jpg",
//     title: "Life experience with cartoons",
//     price: 90,
//     star: "",
//     reviewCount: 5.5,
//     rating: "5.7",
//     country: "Zambia",
//   },
// ];
